TRY:
  distance: 100 # -1 - чтобы глобально
  success: '%player %message &a[Удачно]'
  failed: '%player %message &c[Неудачно]'

ME:
  distance: 100 # -1 - чтобы глобально
  message: '&e* &f%player %message'

ONLINE-BOOK:
  enabled: false
  online: ' &a(онлайн)'
  offline: ' &c(оффлайн)'

HIDE-TAGS:
  enabled: false
  actionbar: '%name'

messages:
  # Оставь пустым, чтобы отключить проверку.
  no-permission: '&cУ тебя недостаточно прав для этого'
  unknown: '&eЯ не знаю такую команду!'