name: '${project.name}'
version: '${project.version}'
main: t.me.tom8hawk.RPplugin
author: https://t.me/tom8hawk
softdepend: [ ProtocolLib ]
api-version: 1.16

commands:
  rppl: { }
  try:
    aliases: [ me ]